name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: your-bucket-name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Zip Artifacts
        run: zip -r app.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AKIA52TL7CFTH3AEVWFL }}
          aws-secret-access-key: ${{ secrets.FS7y5mvspbN1YkMgs+s+m7XqL0XQOnKnnCfcY2xV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp app.zip s3://${{ env.S3_BUCKET_NAME }}/app.zip
